### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Kpaubert** [FredrikAugust/atlas#19]
Love the library, but I think it could be helpful with a more in-depth README. The docs are 🔥  though.

**Comment by Kpaubert** [comment]
Update: The README is very good, but dark mode makes it look like it's empty.

**Comment by kharann** [comment]
XXXXXXXXXXXXXDDDDDDDDDDDDDDD

**Comment by FredrikAugust** [comment]
Thanks for your input, @kharann
